In [1]:
import torch

In [4]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)
y = torch.flatten(x, start_dim=1)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
x = torch.eye(2, 3, dtype=torch.float32)
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.]])


In [15]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([[1,], [2,], [3,], [4,]])
x2 = torch.reshape(x, (-1, 4))
print(y.size(0))
print(x.size())
print(x2.size())
print(y.size())
z = x @ y
z2 = x2 @ y
print(z.size())
print(z2.size())

4
torch.Size([4])
torch.Size([1, 4])
torch.Size([4, 1])
torch.Size([1])
torch.Size([1, 1])


In [25]:
x = torch.ones(3, 2)
x2 = torch.nn.functional.relu(x)
x3 = x2.sum(0)
x4 = torch.ones(x.size())
x5 = torch.heaviside(x, x4)
print(x2)
print(x3)
print(x5)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([3., 3.])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [27]:
b = torch.tensor(torch.rand(1), requires_grad=True)
print(b.size())

torch.Size([1])


C:\Users\lcp\AppData\Local\Temp\ipykernel_20112\755995952.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b = torch.tensor(torch.rand(1), requires_grad=True)


In [30]:
x = torch.tensor([1, 2, 3])
y = x - 1
z = (x == 1)
z2 = z.sum(0)
print(y)
print(z)
print(z2)

tensor([0, 1, 2])
tensor([ True, False, False])
tensor(1)


In [36]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([1, 3, 2])
z = (x == y)
print(z)
print(z.sum().item())
print(x.max().item())

tensor([ True, False, False])
1
3


In [19]:
attn = torch.rand(3, 3)
print(attn)
attn_mask = torch.ones(3, 3)
attn_mask = torch.triu(attn_mask, diagonal=1)
print(attn_mask)
attn_mask = attn_mask.bool()
print(attn_mask)
attn = attn.masked_fill(attn_mask, float('-inf'))
print(attn)


tensor([[0.5996, 0.6894, 0.7799],
        [0.4275, 0.3010, 0.1527],
        [0.7582, 0.6251, 0.9242]])
tensor([[0., 1., 1.],
        [0., 0., 1.],
        [0., 0., 0.]])
tensor([[False,  True,  True],
        [False, False,  True],
        [False, False, False]])
tensor([[0.5996,   -inf,   -inf],
        [0.4275, 0.3010,   -inf],
        [0.7582, 0.6251, 0.9242]])


In [11]:
a = torch.rand(1, 3)
print(a)
b, x = torch.max(a, 1)
print(b)
print(x)

tensor([[0.4168, 0.6293, 0.0227]])
tensor([0.6293])
tensor([1])


In [ ]:
x = torch.tensor([[1, 2, 3], [1, 2, 3]])
print(x, x.size())
print([x])

tensor([[1, 2, 3],
        [1, 2, 3]]) torch.Size([2, 3])
[tensor([[1, 2, 3],
        [1, 2, 3]])]


In [2]:
data = "Harry Potter and the Sorcerer's Stone\n\nCHAPTER ONE\r\nTHE BOY WHO LIVED"
print(data) 

Harry Potter and the Sorcerer's Stone

CHAPTER ONE
THE BOY WHO LIVED


In [24]:
with open("aud-vis\programming3\data\harry_potter.txt") as f:
    data = f.read(2048)
# print(data)
# print(type(data))
data = data.replace(" \n", " #").split()
print(data)
print(type(data))
# data.split()


['Harry', 'Potter', 'and', 'the', "Sorcerer's", 'Stone', '#', 'CHAPTER', 'ONE', '#', 'THE', 'BOY', 'WHO', 'LIVED', '#', 'Mr.', 'and', 'Mrs.', 'Dursley,', 'of', 'number', 'four,', 'Privet', 'Drive,', 'were', 'proud', 'to', 'say', 'that', 'they', 'were', 'perfectly', 'normal,', 'thank', 'you', 'very', 'much.', 'They', 'were', 'the', 'last', 'people', "you'd", 'expect', 'to', 'be', 'involved', 'in', 'anything', 'strange', 'or', 'mysterious,', 'because', 'they', 'just', "didn't", 'hold', 'with', 'such', 'nonsense.', '#', 'Mr.', 'Dursley', 'was', 'the', 'director', 'of', 'a', 'firm', 'called', 'Grunnings,', 'which', 'made', 'drills.', 'He', 'was', 'a', 'big,', 'beefy', 'man', 'with', 'hardly', 'any', 'neck,', 'although', 'he', 'did', 'have', 'a', 'very', 'large', 'mustache.', 'Mrs.', 'Dursley', 'was', 'thin', 'and', 'blonde', 'and', 'had', 'nearly', 'twice', 'the', 'usual', 'amount', 'of', 'neck,', 'which', 'came', 'in', 'very', 'useful', 'as', 'she', 'spent', 'so', 'much', 'of', 'her', 'ti

In [ ]:
voc2ind = {}
voc2ind["A"] = 1
print(voc2ind)

{'A': 1}


In [29]:
attn_mask = torch.full((4, 4), float('-inf'))
attn_mask = torch.triu(attn_mask, diagonal=1) # only keep the upper triangle
print(attn_mask)

tensor([[0., -inf, -inf, -inf],
        [0., 0., -inf, -inf],
        [0., 0., 0., -inf],
        [0., 0., 0., 0.]])


In [34]:
import math
max_len = 5000
d_model = 512
pe = torch.zeros(max_len, d_model)
pos = torch.arange(0, max_len).float() # 0:1:max_len
print(pos.size())
pos = pos.unsqueeze(1)
print(pos.size())
denominator = torch.exp(torch.arange(0, d_model, 2)).float() * (-math.log(10000.0) / d_model) # 10000^{2i/d_model}
print(denominator.size())
print((pos * denominator).size())
pe[:, 0::2] = torch.sin(pos * denominator)
pe[:, 1::2] = torch.cos(pos * denominator)
print(pe)

torch.Size([5000])
torch.Size([5000, 1])
torch.Size([256])
torch.Size([5000, 256])
tensor([[-0.0000,  1.0000, -0.0000,  ...,     nan,     nan,     nan],
        [-0.0180,  0.9998, -0.1325,  ...,     nan,     nan,     nan],
        [-0.0360,  0.9994, -0.2627,  ...,     nan,     nan,     nan],
        ...,
        [-0.9375, -0.3479,  0.9716,  ...,     nan,     nan,     nan],
        [-0.9311, -0.3647,  0.9944,  ...,     nan,     nan,     nan],
        [-0.9244, -0.3814,  0.9996,  ...,     nan,     nan,     nan]])


In [43]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 4, 4])
z = torch.concat((x, y), 0)
print(z)

tensor([1, 2, 3, 4, 4, 4])


In [48]:
x = torch.multinomial(torch.tensor([0.2, 0.4, 0.4]), 1)
print(x)
print(x.size())

tensor([2])
torch.Size([1])
