In [2]:
import torch

In [4]:
x = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(x)
y = torch.flatten(x, start_dim=1)
print(y)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1, 2, 3],
        [4, 5, 6]])


In [3]:
x = torch.eye(2, 3, dtype=torch.float32)
print(x)

tensor([[1., 0., 0.],
        [0., 1., 0.]])


In [15]:
x = torch.tensor([1, 2, 3, 4])
y = torch.tensor([[1,], [2,], [3,], [4,]])
x2 = torch.reshape(x, (-1, 4))
print(y.size(0))
print(x.size())
print(x2.size())
print(y.size())
z = x @ y
z2 = x2 @ y
print(z.size())
print(z2.size())

4
torch.Size([4])
torch.Size([1, 4])
torch.Size([4, 1])
torch.Size([1])
torch.Size([1, 1])


In [25]:
x = torch.ones(3, 2)
x2 = torch.nn.functional.relu(x)
x3 = x2.sum(0)
x4 = torch.ones(x.size())
x5 = torch.heaviside(x, x4)
print(x2)
print(x3)
print(x5)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([3., 3.])
tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])


In [27]:
b = torch.tensor(torch.rand(1), requires_grad=True)
print(b.size())

torch.Size([1])


C:\Users\lcp\AppData\Local\Temp\ipykernel_20112\755995952.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  b = torch.tensor(torch.rand(1), requires_grad=True)


In [30]:
x = torch.tensor([1, 2, 3])
y = x - 1
z = (x == 1)
z2 = z.sum(0)
print(y)
print(z)
print(z2)

tensor([0, 1, 2])
tensor([ True, False, False])
tensor(1)


In [33]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([1, 3, 2])
z = (x == y)
print(z)
print(z.sum().item())

tensor([ True, False, False])
1


In [19]:
attn = torch.rand(3, 3)
print(attn)
attn_mask = torch.ones(3, 3)
attn_mask = torch.triu(attn_mask, diagonal=1)
print(attn_mask)
attn_mask = attn_mask.bool()
print(attn_mask)
attn = attn.masked_fill(attn_mask, float('-inf'))
print(attn)


tensor([[0.5996, 0.6894, 0.7799],
        [0.4275, 0.3010, 0.1527],
        [0.7582, 0.6251, 0.9242]])
tensor([[0., 1., 1.],
        [0., 0., 1.],
        [0., 0., 0.]])
tensor([[False,  True,  True],
        [False, False,  True],
        [False, False, False]])
tensor([[0.5996,   -inf,   -inf],
        [0.4275, 0.3010,   -inf],
        [0.7582, 0.6251, 0.9242]])


In [11]:
a = torch.rand(1, 3)
print(a)
b, x = torch.max(a, 1)
print(b)
print(x)

tensor([[0.4168, 0.6293, 0.0227]])
tensor([0.6293])
tensor([1])
